### ISSUE TITLE
Viewing logs/details on federation activities

### ISSUE THREAD

**Issue by Demigodrick** [Nutomic/ibis#31]
Is there a way to see what is happening in terms of federation on the server? I have a couple of discrepancies where edits don't seem to federate. For example:

https://ibis.wiki/article/Setup_Instructions/history - this has the edit by salamander
https://wiki.lemmy.zip/article/Setup_Instructions@ibis.wiki/history - this doesnt have the edit

https://wiki.lemmy.zip/ - main page has image
https://open.ibis.wiki/article/Main_Page@wiki.lemmy.zip - main page edit not received

**Comment by Nutomic** [comment]
Did you follow the remote instance in those cases? You can do this by pasting the instance url (eg `https://wiki.lemmy.zip/`) in the search field and clicking the follow button.

**Comment by Nutomic** [comment]
That error message is just because I didnt code the frontend well, its nothing to worry about. 

In case of open.ibis.wiki I can see in the db that no local user is following wiki.lemmy.zip (`select * from instance_follow;`, `select id,domain from instance;`) so its normal that changes are not synchronized. So in that case changes would only get synchronized at most once every 24 hours. Ive followed no from open.ibis.wiki so if you make another edit it should federate.

I assume in the other case its the same, you need to follow ibis.wiki. This functionality should be more obvious in the UI. Maybe with a "follow instance" button on the article page?

**Comment by Demigodrick** [comment]
Ah yeah perfect the main page edit has federated to open.ibis.wiki.

The instance has been following ibis.wiki from creation, so would the fact the third party (wiki.mander.xyz) made the change before I was federated with wiki.mander.xyz have any impact, or should ibis.wiki have pushed that change to wiki.lemmy.zip? I can check again at the 24 hour mark after edit and see if its federated across at that point.

**Comment by Nutomic** [comment]
ibis.wiki would only send edits to your instance after following. Also your instance should fetch all articles and edits from ibis.wiki when first interacting with it, and later every 24h at most.
